### PR TITLE
Implementation till now

### PR DESCRIPTION
**Pull request by sonutiwari**

### CODE REVIEW

**Comment by sonutiwari** [comment]
implemented all the basic tasks. will be looking for improvements now.

**Comment by sonutiwari** [comment]
Project of week 3 Day 1 and 2.

**Comment by sonutiwari** [comment]
Week 4 Day 1 Assignment.

**Comment by sonutiwari** [comment]
please review the assignment

**Comment by arkesh92** [comment]
Assignment complete

**Pull request closed without merging**
